export type APIEvent =
    'getPosts'
    | 'createPost'
    | 'deletePost'
    | 'postsUpdate'
    | 'getLikes'
    | 'unlike'
    | 'createLike'
    | 'getUsers'
    | 'getUser'
    | 'usersUpdate'
    | 'editProfilePic'
    | 'editEmail'
    | 'createComment'
    | 'deleteComment'
    | 'errorHandler'
    ;
